import argparse
import json
import logging
import os
from pathlib import Path

import torch
from langchain.output_parsers import PydanticOutputParser
from PIL import Image

from layoutlib.hfds import hfds_helper_factory, sample_example
from layoutlib.hfds.clustering import clustering_default_weight_path_factory
from layoutlib.hfds.util import extract_class_label_mappings
from layoutlib.manager import LayoutManager
from layoutlib.schema import get_layout_pydantic_model
from opencole.inference.tester import TypographyLMMTester
from opencole.schema import DetailV1, Detail

logging.basicConfig(level=os.environ.get("LOGLEVEL", "INFO"))
logger = logging.getLogger(__name__)

torch.set_default_dtype(torch.float16)


def main(DetailClass: type[Detail]) -> None:
    parser = argparse.ArgumentParser()
    TypographyLMMTester.register_args(parser)

    parser.add_argument("--hfds_name", type=str, default="crello")
    parser.add_argument("--schema_name", type=str, default="typography_crello_default")
    # I/O
    parser.add_argument(
        "--detail_dir",
        type=str,
        required=True,
        help="directory containing a generated design plan given an intention.",
    )
    parser.add_argument(
        "--image_dir",
        type=str,
        required=True,
        help="directory containing a single image generated by text-to-image given a detail.",
    )
    parser.add_argument("--output_dir", type=str, required=True)
    # llava model
    parser.add_argument(
        "--pretrained_model_name_or_path",
        type=str,
        required=True,
    )
    parser.add_argument("--load_in_4bit", action="store_true")
    parser.add_argument("--load_in_8bit", action="store_true")
    parser.set_defaults(max_new_tokens=1024)
    args = parser.parse_args()
    logger.info(f"{args=}")

    output_dir = Path(args.output_dir)
    if not output_dir.exists():
        output_dir.mkdir(parents=True, exist_ok=True)

    _, features = sample_example(args.hfds_name)
    class_label_mappings = extract_class_label_mappings(features)
    layout_manager = LayoutManager(
        schema_name=args.schema_name,
        weight_path=clustering_default_weight_path_factory(args.hfds_name),
        class_label_mappings=class_label_mappings,
    )
    layout_parser = PydanticOutputParser(  # type: ignore
        pydantic_object=get_layout_pydantic_model(
            schema=layout_manager.schema,
            class_label_mappings=layout_manager.class_label_mappings,
        )  # type: ignore
    )
    hfds_helper = hfds_helper_factory(hfds_name=args.hfds_name, features=features)

    tester_kwargs = {
        k: v
        for k, v in vars(args).items()
        if k
        not in ["detail_dir", "image_dir", "output_dir", "hfds_name", "schema_name"]
    }
    tester = TypographyLMMTester(
        layout_parser=layout_parser,
        layout_manager=layout_manager,
        hfds_helper=hfds_helper,
        **tester_kwargs,
    )

    details = list(Path(args.detail_dir).glob("*.json"))
    images = list(Path(args.image_dir).glob("*.png"))
    assert len(details) == len(images) and len(details) > 0
    assert set([x.stem for x in details]) == set([x.stem for x in images])
    detail_image_pairs = [(x, y) for x, y in zip(sorted(details), sorted(images))]
    if tester.use_chunking:
        detail_image_pairs = tester.get_chunk(detail_image_pairs)

    for i, (detail_path, image_path) in enumerate(detail_image_pairs):
        image = Image.open(str(image_path))
        with detail_path.open("r") as fp:
            detail = DetailClass(**json.load(fp))
        output_path = output_dir / f"{detail_path.stem}.json"
        if output_path.exists():
            logger.info(f"Skipping {detail_path.stem} since it already exists.")
            continue

        output = tester(image, detail)
        if output is None:
            with output_path.open("w") as fp:
                json.dump({}, fp, indent=4)
        else:
            with output_path.open("w") as fp:
                json.dump(output, fp, indent=4)

        if os.environ.get("LOGLEVEL", "INFO") == "DEBUG" and i == 9:
            break


if __name__ == "__main__":
    main(DetailClass=DetailV1)
